# Generated by Django 3.1.3 on 2020-11-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_auto_20201114_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='picture',
            field=models.ImageField(blank=True, null=None, upload_to='tweet_pic/'),
        ),
    ]
