# Generated by Django 3.1.3 on 2020-11-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_auto_20201119_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='tweet_pic/'),
        ),
    ]
